### ISSUE TITLE
Can't build and run

### ISSUE THREAD

**Issue by mahmoudajawad** [rhmoller/blobs-and-bullets#10]
Can you confirm versions for node, npm?

I'm getting:
```
[webpack-cli] Failed to load '/workspace/blobs-and-bullets/webpack.config.js' config
[webpack-cli] Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] should be an object:
   object { patterns, options? }
```

npm: 6.14.13
node: 14.17.0

**Comment by rhmoller** [comment]
Some of the dependencies must have changed since last time I ran this project. I got the same error as you today.

I have updated the webpack configuration. Please try again and let me know how it turns out.

**Comment by mahmoudajawad** [comment]
I confirm the game launches now, though I can't play it as the characters don't move whatever I do. What are the controls? I'm using MS Edge (`91.0.864.41 (Official build) (x86_64)`) on macos `10.15.7`.

**Comment by rhmoller** [comment]
That is a weak spot in the code. It is hardcoded to work with an PS4 Dual Shock controller on Firefox in Windows. If you have another gamepad you can change the constants here to match your controller: https://github.com/rhmoller/blobs-and-bullets/blob/master/src/engine/mod.rs#L26

If you want to add keyboard support, you can replace this code that polls gamepads: https://github.com/rhmoller/blobs-and-bullets/blob/master/src/engine/mod.rs#L74

**Comment by mahmoudajawad** [comment]
Cool. I wanted to know if it is building correctly, or something is breaking.

May I suggest you mention this in README?

I'm closing this for now.
